const fs = require('fs');

let content = fs.readFileSync('src/data/dsaTopicsContent.jsx', 'utf8');

// 1. isPalindrome snippet replacement
const palTarget = '    code: {\n      cpp: `#include <iostream>\\nusing namespace std;\\n\\nclass Node {\\npublic:\\n    int data;\\n    Node* next;\\n    Node* prev; // For Doubly Linked List\\n    Node(int data) {\\n        this->data = data;\\n        this->next = nullptr;\\n        this->prev = nullptr;\\n    }\\n};\\n\\n// --- Main Logic ---\\n// C++ snippet\\n// 1. Find middle using fast and slow pointers.\\n// 2. Reverse the second half.\\n// 3. Compare the first half and reversed second half element by element.\\n// 4. (Optional) Reverse the second half again to restore original list.`,\n      java: `import java.util.*;\\n\\nclass Node {\\n    int data;\\n    Node next;\\n    Node prev; // For Doubly Linked List\\n    Node(int data) {\\n        this.data = data;\\n        this.next = null;\\n        this.prev = null;\\n    }\\n}\\n\\n// --- Main Logic ---\\n// Java snippet\\n// This combines middleNode + reverseList functions.\\npublic boolean isPalindrome(Node head) {\\n    // Left as an exercise to assemble!\\n    return true;\\n}`,\n    },';

const palReplacement = `    code: {
      cpp: "#include <iostream>\\nusing namespace std;\\n\\nclass Node {\\npublic:\\n    int data;\\n    Node* next;\\n    Node* prev;\\n    Node(int data) {\\n        this->data = data;\\n        this->next = nullptr;\\n        this->prev = nullptr;\\n    }\\n};\\n\\n// --- Main Logic ---\\nNode* reverseList(Node* head) {\\n    Node* prev = nullptr;\\n    Node* curr = head;\\n    while(curr != nullptr) {\\n        Node* nextTemp = curr->next;\\n        curr->next = prev;\\n        prev = curr;\\n        curr = nextTemp;\\n    }\\n    return prev;\\n}\\n\\nbool isPalindrome(Node* head) {\\n    if (head == nullptr || head->next == nullptr) return true;\\n    Node* slow = head;\\n    Node* fast = head;\\n    while (fast->next != nullptr && fast->next->next != nullptr) {\\n        slow = slow->next;\\n        fast = fast->next->next;\\n    }\\n    slow->next = reverseList(slow->next);\\n    slow = slow->next;\\n    Node* dummy = head;\\n    while (slow != nullptr) {\\n        if (dummy->data != slow->data) return false;\\n        dummy = dummy->next;\\n        slow = slow->next;\\n    }\\n    return true;\\n}",
      java: "import java.util.*;\\n\\nclass Node {\\n    int data;\\n    Node next;\\n    Node prev;\\n    Node(int data) {\\n        this.data = data;\\n        this.next = null;\\n        this.prev = null;\\n    }\\n}\\n\\n// --- Main Logic ---\\nprivate Node reverseList(Node head) {\\n    Node prev = null;\\n    Node curr = head;\\n    while(curr != null) {\\n        Node nextTemp = curr.next;\\n        curr.next = prev;\\n        prev = curr;\\n        curr = nextTemp;\\n    }\\n    return prev;\\n}\\n\\npublic boolean isPalindrome(Node head) {\\n    if (head == null || head.next == null) return true;\\n    Node slow = head;\\n    Node fast = head;\\n    while (fast.next != null && fast.next.next != null) {\\n        slow = slow.next;\\n        fast = fast.next.next;\\n    }\\n    slow.next = reverseList(slow.next);\\n    slow = slow.next;\\n    Node dummy = head;\\n    while (slow != null) {\\n        if (dummy.data != slow.data) return false;\\n        dummy = dummy.next;\\n        slow = slow.next;\\n    }\\n    return true;\\n}",
    },`;

// 2. k-group
const kgTarget = '    code: {\n      cpp: `#include <iostream>\\nusing namespace std;\\n\\nclass Node {\\npublic:\\n    int data;\\n    Node* next;\\n    Node* prev; // For Doubly Linked List\\n    Node(int data) {\\n        this->data = data;\\n        this->next = nullptr;\\n        this->prev = nullptr;\\n    }\\n};\\n\\n// --- Main Logic ---\\n// C++ snippet\\n// Helper reversed and length functions usually required\\n// It acts as an extension of standard linkedlist reverse`,\n      java: `import java.util.*;\\n\\nclass Node {\\n    int data;\\n    Node next;\\n    Node prev; // For Doubly Linked List\\n    Node(int data) {\\n        this.data = data;\\n        this.next = null;\\n        this.prev = null;\\n    }\\n}\\n\\n// --- Main Logic ---\\n// Java snippet\\n// Hard level interview problem.`,\n    },';

const kgReplacement = `    code: {
      cpp: "#include <iostream>\\nusing namespace std;\\n\\nclass Node {\\npublic:\\n    int data;\\n    Node* next;\\n    Node* prev;\\n    Node(int data) {\\n        this->data = data;\\n        this->next = nullptr;\\n        this->prev = nullptr;\\n    }\\n};\\n\\n// --- Main Logic ---\\nint lengthOfLinkedList(Node* head) {\\n    int length = 0;\\n    while(head != nullptr) {\\n        ++length;\\n        head = head->next;\\n    }\\n    return length;\\n}\\n\\nNode* reverseKGroup(Node* head, int k) {\\n    if(head == nullptr || head->next == nullptr || k <= 1) return head;\\n    int length = lengthOfLinkedList(head);\\n    \\n    Node* dummyHead = new Node(0);\\n    dummyHead->next = head;\\n    Node* pre = dummyHead;\\n    Node* cur;\\n    Node* nex;\\n    \\n    while(length >= k) {\\n        cur = pre->next;\\n        nex = cur->next;\\n        for(int i=1;i<k;i++) {\\n            cur->next = nex->next;\\n            nex->next = pre->next;\\n            pre->next = nex;\\n            nex = cur->next;\\n        }\\n        pre = cur;\\n        length -= k;\\n    }\\n    Node* newHead = dummyHead->next;\\n    delete dummyHead;\\n    return newHead;\\n}",
      java: "import java.util.*;\\n\\nclass Node {\\n    int data;\\n    Node next;\\n    Node prev;\\n    Node(int data) {\\n        this.data = data;\\n        this.next = null;\\n        this.prev = null;\\n    }\\n}\\n\\n// --- Main Logic ---\\npublic int lengthOfLinkedList(Node head) {\\n    int length = 0;\\n    while(head != null) {\\n        ++length;\\n        head = head.next;\\n    }\\n    return length;\\n}\\n\\npublic Node reverseKGroup(Node head, int k) {\\n    if(head == null || head.next == null || k <= 1) return head;\\n    int length = lengthOfLinkedList(head);\\n    \\n    Node dummyHead = new Node(0);\\n    dummyHead.next = head;\\n    Node pre = dummyHead;\\n    Node cur;\\n    Node nex;\\n    \\n    while(length >= k) {\\n        cur = pre.next;\\n        nex = cur.next;\\n        for(int i=1;i<k;i++) {\\n            cur.next = nex.next;\\n            nex.next = pre.next;\\n            pre.next = nex;\\n            nex = cur.next;\\n        }\\n        pre = cur;\\n        length -= k;\\n    }\\n    return dummyHead.next;\\n}",
    },`;

// 3. clone random
const crTarget = '    code: {\n      cpp: `#include <iostream>\\nusing namespace std;\\n\\nclass Node {\\npublic:\\n    int data;\\n    Node* next;\\n    Node* prev; // For Doubly Linked List\\n    Node(int data) {\\n        this->data = data;\\n        this->next = nullptr;\\n        this->prev = nullptr;\\n    }\\n};\\n\\n// --- Main Logic ---\\n// C++ // Medium-Hard level\\n// 1. Interweave new nodes\\n// 2. Map random pointers\\n// 3. Detach original and cloned nodes cleanly`,\n      java: `import java.util.*;\\n\\nclass Node {\\n    int data;\\n    Node next;\\n    Node prev; // For Doubly Linked List\\n    Node(int data) {\\n        this.data = data;\\n        this.next = null;\\n        this.prev = null;\\n    }\\n}\\n\\n// --- Main Logic ---\\n// Java // Medium-Hard level`,\n    },';

const crReplacement = `    code: {
      cpp: "#include <iostream>\\nusing namespace std;\\n\\nclass Node {\\npublic:\\n    int data;\\n    Node* next;\\n    Node* random; // Random pointer\\n    Node(int data) {\\n        this->data = data;\\n        this->next = nullptr;\\n        this->random = nullptr;\\n    }\\n};\\n\\n// --- Main Logic ---\\nNode* copyRandomList(Node* head) {\\n    Node* iter = head; \\n    Node* front = head;\\n    // Step 1: Clone and interweave\\n    while (iter != nullptr) {\\n        front = iter->next;\\n        Node* copy = new Node(iter->data);\\n        iter->next = copy;\\n        copy->next = front;\\n        iter = front;\\n    }\\n    // Step 2: Assign random pointers\\n    iter = head;\\n    while (iter != nullptr) {\\n        if (iter->random != nullptr) {\\n            iter->next->random = iter->random->next;\\n        }\\n        iter = iter->next->next;\\n    }\\n    // Step 3: Extract copy\\n    iter = head;\\n    Node* pseudoHead = new Node(0);\\n    Node* copy = pseudoHead;\\n    while (iter != nullptr) {\\n        front = iter->next->next;\\n        copy->next = iter->next;\\n        iter->next = front;\\n        copy = copy->next;\\n        iter = front;\\n    }\\n    Node* res = pseudoHead->next;\\n    delete pseudoHead;\\n    return res;\\n}",
      java: "import java.util.*;\\n\\nclass Node {\\n    int data;\\n    Node next;\\n    Node random;\\n    Node(int data) {\\n        this.data = data;\\n        this.next = null;\\n        this.random = null;\\n    }\\n}\\n\\n// --- Main Logic ---\\npublic Node copyRandomList(Node head) {\\n    Node iter = head; \\n    Node front = head;\\n    // Step 1: Clone and interweave\\n    while (iter != null) {\\n        front = iter.next;\\n        Node copy = new Node(iter.data);\\n        iter.next = copy;\\n        copy.next = front;\\n        iter = front;\\n    }\\n    // Step 2: Assign random pointers\\n    iter = head;\\n    while (iter != null) {\\n        if (iter.random != null) {\\n            iter.next.random = iter.random.next;\\n        }\\n        iter = iter.next.next;\\n    }\\n    // Step 3: Extract copy\\n    iter = head;\\n    Node pseudoHead = new Node(0);\\n    Node copy = pseudoHead;\\n    while (iter != null) {\\n        front = iter.next.next;\\n        copy.next = iter.next;\\n        iter.next = front;\\n        copy = copy.next;\\n        iter = front;\\n    }\\n    return pseudoHead.next;\\n}",
    },`;

if (content.includes(palTarget)) content = content.replace(palTarget, palReplacement);
if (content.includes(kgTarget)) content = content.replace(kgTarget, kgReplacement);
if (content.includes(crTarget)) content = content.replace(crTarget, crReplacement);

fs.writeFileSync('src/data/dsaTopicsContent.jsx', content);
console.log('Done replacement script!');
